### ISSUE TITLE
Doesn't Work When App is Quit

### ISSUE THREAD

**Issue by Avakining** [chockenberry/Notchmeister#2]
Could Notchmeister be a Menu Bar app or otherwise run in the background so it doesn't have to be on the dock to work?

**Comment by chockenberry** [comment]
When the Dock icon is turned off there is no menubar or other way to interact with the app after the main window is closed.

Since we purposely don't process any events happening near or underneath the notch, that means there's no way to make the window reappear to control the app.

A menubar item would be possible, but I'm not convinced that's a better use of screen real estate.

**Comment by dimitribouniol** [comment]
I seem to remember that apps that choose to hide their dock icon will show it again if the app is "relaunched", which could be a sufficient way when accompanied by a warning to allow the user to properly quit it etc…

**Comment by tbradsha** [comment]
Perhaps clicking while in the notch can bring the main window up?

**Comment by asyncro** [comment]
> A menubar item would be possible, but I'm not convinced that's a better use of screen real estate.

It would be a better use for those who use utilities like Bartender that let us selectively hide menubar items.

**Comment by Gerzer** [comment]
What about having the app just be a control panel for a separate dæmon process that actually renders the effects without either a Menu Bar item or an icon in the Dock? You could even package it as a [preference pane](https://developer.apple.com/documentation/preferencepanes) instead of as a standalone app to make it clear that its purpose is to configure a visual effect that applies systemwide.

**Comment by chockenberry** [comment]
@Gerzer As far as I know, a preference pane can't be distributed on the Mac App Store. I agree that that would be the best approach, but I can also see how Apple wouldn't want an easy way for customers to install system-wide configuration (would be _trivial_ to abuse).

@asyncro Bartender is a great app, but it's far from a universal feature. Most folks let menu bar items pile up without any kind of management.

**Comment by toddjonker** [comment]
> I seem to remember that apps that choose to hide their dock icon will show it again if the app is "relaunched", which could be a sufficient way when accompanied by a warning to allow the user to properly quit it etc…

Moom works this way.

**Comment by asyncro** [comment]
> @asyncro Bartender is a great app, but it's far from a universal feature. Most folks let menu bar items pile up without any kind of management.

True. The ask (edit: my ask) isn't to replace the dock item with a menu bar item, but simply give us the option to choose one or the other. Power users who likely have Bartender or similar (and the ones most likely to have stumbled upon Notchmeister in the first place) will be satisfied.

**Comment by chockenberry** [comment]
I think I've found a good solution without the need for a menu bar icon: any click under (or near) the notch will re-open the settings window. The only hangup here may be App Review (which may require some kind of visual affordance to be on screen).

For those of you who are interested, there's a public TestFlight: https://testflight.apple.com/join/pIGViV74

**Comment by dimitribouniol** [comment]
Can I just say, I _love_ this little control panel 😍 (please excuse the broken effects in screenshot)

<img width="242" alt="image" src="https://user-images.githubusercontent.com/225505/147516461-aa863e59-1fc6-4a4a-b578-ee293552fdf2.png">

**Comment by chockenberry** [comment]
Closing this issue since there hasn't been any negative feedback since for the past 10 days.

Hopefully, App Review won't make me re-open it :-)
