### ISSUE TITLE
Some effects not showing / staying correctly

### ISSUE THREAD

**Issue by ffried** [chockenberry/Notchmeister#27]
~The "Nano Radar"~ Some effects no longer stays on screen correctly. I already noticed this in the last beta, but forgot to report it.

https://github.com/chockenberry/Notchmeister/assets/1689782/34020650-2338-4d9c-b705-dbaa08ac6c98

*Note:*
Interestingly, this doesn't happen if the Notchmeister settings window is active.

**Edit:**
Having found out this, I tested the other effects again, and the following effects seem to have a very similar issue:
- Glow
- Plasma Leak (the sparks stop when the mouse no longer moves vs. continue where the settings window is active)
- Expando

**Comment by chockenberry** [comment]
Wow. This is a good find!

It turns out that some of recent changes with adding multiple windows made macOS buggy when getting the mouse location from a moved event (it was returning a value in screen coordinates, not window coordinates). I think I have a workaround and it will be in the next release.

It could also explain some other weird behavior folks were seeing.

**Comment by chockenberry** [comment]
I just uploaded build 38 to TestFlight, please let me know if it fixes the problem for you and I'll close the issue.

**Comment by ffried** [comment]
Thanks a lot! I'll try it tomorrow and will let you know. Or actually, I'll just close the issue if it's resolved.

**Comment by ffried** [comment]
Just tried the new build and the effects work perfectly fine again now! Thanks!
